### ISSUE TITLE
rlsd website no longer works

### ISSUE THREAD

**Issue by josefnpat** [dimkr/rlsd#67]
It seems that `http://rlsd.dimakrasner.com/` now points to `http://dimakrasner.com/`.

There is a link on the page, but it points to `https://rlsd2.dimakrasner.com/` which gives a `ERR_CONNECTION_REFUSED` when it should point to `http://rlsd2.dimakrasner.com/`

Could you please forward:

`http://rlsd.dimakrasner.com/` to `http://rlsd2.dimakrasner.com/` and
`https://rlsd2.dimakrasner.com/` to `http://rlsd2.dimakrasner.com/` (or fix the error)

**Comment by dimkr** [comment]
Changed to HTTP - that server does not support TLS. Thanks!

**Comment by josefnpat** [comment]
:heart:
